#!/bin/bash
# 最终验证和展示脚本

clear
echo "=========================================="
echo "  🎉 Qwen3.5 训练方案已完成！"
echo "=========================================="
echo ""

# 统计信息
SCRIPTS=$(ls -1 *.sh 2>/dev/null | wc -l)
DOCS=$(ls -1 *.md 2>/dev/null | grep -E "快速|配置|README|开始|索引|QWEN" | wc -l)

echo "📦 创建的文件统计："
echo "  - 脚本文件: $SCRIPTS 个"
echo "  - 文档文件: $DOCS 个"
echo ""

echo "=========================================="
echo "  核心工具（三大脚本）"
echo "=========================================="
echo ""
echo "1️⃣  run_qwen35_configurable.sh (8.4K) ⭐⭐⭐"
echo "    功能最强的可配置训练脚本"
echo "    - 调整 GPU 数量: NGPU=8"
echo "    - 调整并行策略: DP_SHARD=4 TP=2 PP=2"
echo "    - 自动输出: Loss、显存、性能"
echo ""
echo "2️⃣  examples_qwen35_training.sh (2.6K) ⭐⭐"
echo "    12 种预设配置，菜单式选择"
echo ""
echo "3️⃣  monitor_training.sh (2.4K) ⭐⭐"
echo "    7 种监控模式，实时查看训练状态"
echo ""

echo "=========================================="
echo "  核心文档（必读）"
echo "=========================================="
echo ""
echo "📖 文件索引.md (8.8K)"
echo "   完整的文件清单和索引"
echo ""
echo "📖 开始使用_README.md (9.5K) 👈 从这里开始！"
echo "   立即开始的完整指南"
echo ""
echo "📖 可配置训练脚本使用指南.md (11K)"
echo "   详细的参数说明和使用场景"
echo ""

echo "=========================================="
echo "  快速开始（三选一）"
echo "=========================================="
echo ""
echo "方式 1: 使用示例选择器"
echo "  $ bash examples_qwen35_training.sh"
echo ""
echo "方式 2: 快速测试（1 步）"
echo "  $ STEPS=1 bash run_qwen35_configurable.sh"
echo ""
echo "方式 3: 自定义配置"
echo "  $ NGPU=8 DP_SHARD=4 TP=2 bash run_qwen35_configurable.sh"
echo ""

echo "=========================================="
echo "  实时查看精度、显存、性能"
echo "=========================================="
echo ""
echo "方法 1: 训练时终端自动显示"
echo "  Step X/Y | Loss: X.XX | Tokens/sec: XXXX | GPU Mem: XX GB"
echo ""
echo "方法 2: 使用监控脚本（在另一个终端）"
echo "  $ bash monitor_training.sh"
echo "  选项 2: 只看 Loss（精度）"
echo "  选项 3: 只看 Tokens/sec（性能）"
echo "  选项 4: 只看 GPU Mem（显存）"
echo ""
echo "方法 3: TensorBoard 可视化"
echo "  $ tensorboard --logdir ./outputs/"
echo "  浏览器: http://localhost:6006"
echo ""

echo "=========================================="
echo "  GPU 和并行配置示例"
echo "=========================================="
echo ""
echo "单 GPU:"
echo "  $ bash run_qwen35_configurable.sh"
echo ""
echo "4 GPU 数据并行:"
echo "  $ NGPU=4 bash run_qwen35_configurable.sh"
echo ""
echo "8 GPU 混合并行 (DP + TP):"
echo "  $ NGPU=8 DP_SHARD=4 TP=2 bash run_qwen35_configurable.sh"
echo ""
echo "8 GPU 三维并行 (DP + TP + PP):"
echo "  $ NGPU=8 DP_SHARD=2 TP=2 PP=2 bash run_qwen35_configurable.sh"
echo ""

echo "=========================================="
echo "  验证和测试"
echo "=========================================="
echo ""
echo "验证工具链:"
echo "  $ bash test_toolchain.sh"
echo ""
echo "检查环境:"
echo "  $ bash check_qwen35_ready.sh"
echo ""

echo "=========================================="
echo "  推荐工作流"
echo "=========================================="
echo ""
echo "1. 阅读文档"
echo "   $ cat 文件索引.md"
echo "   $ cat 开始使用_README.md"
echo ""
echo "2. 验证环境"
echo "   $ bash test_toolchain.sh"
echo ""
echo "3. 快速测试"
echo "   $ STEPS=1 bash run_qwen35_configurable.sh"
echo ""
echo "4. 启动监控（新终端）"
echo "   $ bash monitor_training.sh"
echo ""
echo "5. 正式训练"
echo "   $ bash run_qwen35_configurable.sh"
echo ""

echo "=========================================="
echo "  完成！所有工具已就绪 ✅"
echo "=========================================="
echo ""
echo "立即开始:"
echo "  $ bash examples_qwen35_training.sh"
echo ""
echo "查看完整文档:"
echo "  $ cat 文件索引.md"
echo ""
